import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  let header = (
    <header>
dsfsdfsdf
    </header>
  )

  let footer = (
    <footer>
<p>Made with 💛</p>
    </footer>
  )
  return (
    <html lang="en">
      <body className={inter.className}>
        {header}
        {children}
        {footer}
        </body>
    </html>
  );
}
